clean:
	-rm -r vmware_test.vmx.lck/M54823.lck vmware_test.vmx.lck vmware.log \
	vmware-0.log vmware-1.log vmware-2.log vmware-3.log vmware-4.log \
	vmware-5.log nvram vmware_test.vmxf vmware_test.vmsd
